import PyMyHealth
import mysql.connector
import argparse

parser = argparse.ArgumentParser(description='PyMyHealth is top for MySQL')
parser.add_argument('-d', '--database', nargs='?', help='Database', default='INFORMATION_SCHEMA', type=str)
parser.add_argument('-u', '--user', nargs='?', help='User', default='root', type=str)
parser.add_argument('-p', '--password', nargs='?', help='Password', default='', type=str)
parser.add_argument('-H', '--host', nargs='?', help='Host to connect to', default='localhost', type=str)
parser.add_argument('-P', '--port', nargs='?', help='Port', default='3306', type=int)
parser.add_argument('-S', '--socket', nargs='?', help='Socket', type=str)
parser.add_argument('-r', '--refresh', nargs='?', help='Screen refresh rate', default='2', type=str)
parser.add_argument('-v', '--verbose', help='Verbose/Debug output', default=False)

args = parser.parse_args()

if args.socket:
    conn = mysql.connector.connect(user=args.user, password=args.password,
                                   host=args.host, unix_socket=args.socket,
                                   database=args.database)
else:
    conn = mysql.connector.connect(user=args.user, password=args.password,
                                   host=args.host, database=args.database)

health = PyMyHealth.PyMyHealth(conn, args.verbose)

# TODO: Rewrite with selected testing framework for Python

i = PyMyHealth.PyMyHealth(conn)
print(i.set_metric('this', 10))
print(i.metrics)
print(i.get_metric('this'))
print(i.set_metric('this', 20))
print(i.get_metric('this'))
print(i.set_metric('this', 25))
print(i.get_metric('this'))
print(i.set_metric('this', 40))
print(i.get_metric('this'))
print(i.metric_history)
for j in range(25):
    i.set_metric('this', j)
    print(i.metric_history)

print(i.query_metric('Com_select', 'status'))
print(i.query_metric('Com_insert', 'status'))
print(i.query_metric('Com_update', 'status'))
print(i.query_metric('Com_delete', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Questions', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.query_metric('Slow_queries', 'status'))
print(i.query_metric('Com_show_status', 'status'))
print(i.info())
print(i.pretty_info())
print(i.uptime())
print(i.pretty_uptime())
print(i.mytop_uptime())
# print(i.query_distribution())
# print(i.pretty_query_distribution())
print(i.pretty_query_distribution_columns())
print(i.thread_distribution())
print(i.pretty_thread_distribution_columns())
print(i.key_efficiency())
print(i.key_efficiency_delta())
print(i.innodb_buffer_pool_status())
print(i.innodb_io_stats())
print(i.innodb_io_stats_delta())
print(i.innodb_io_stats_delta())
print(i.innodb_io_stats_delta())
print(i.innodb_io_stats_delta())
print(i.get_metric_history('Innodb_data_written'))
print(i.get_qps())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_qps_delta())
print(i.get_metric_history('Questions'))
print(i.get_network())
print(i.get_network_delta())
print(i.get_network_delta())
print(i.get_network_delta())
print(i.get_network_delta())
print(i.get_network_delta())
print(i.get_metric_history('Bytes_sent'))
print(i.get_slow_qps())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_slow_delta())
print(i.get_metric_history('Slow_queries'))
print(i.get_lock_waits())
print(i.get_processlist())
print(i.get_processlist(False, True, False))
print(i.get_processlist(True, False, False))
print(i.get_processlist(True, True, True))
print(i.get_processlist(False, False, False))
